$(document).ready(function(){
    $('#boutton1').click(function(){
        $('#comp1').toggle()
    });
    $('#boutton2').click(function(){
        $('#comp2').toggle()
    });
    $('#boutton3').click(function(){
        $('#comp3').toggle()
    });
    $('#boutton4').click(function(){
        $('#comp4').toggle()
    });
    $('#boutton5').click(function(){
        $('#comp5').toggle()
    });
    $('#boutton6').click(function(){
        $('#comp6').toggle()
    });
    $('#boutton7').click(function(){
        $('#comp7').toggle()
    });
     
});